spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@contaspix.hqbpdxt.mongodb.net/?retryWrites=true&w=majority
      database: Clients
  rabbitmq:
    addresses: amqps://soiggbyt:9J6xLVyydcoIEuQeMVlrUMBXVyfi-2qK@jackal.rmq.cloudamqp.com/soiggbyt
  flyway:
    enabled: true
    baseline-version: 1
    locations: [classpath:db/migrations]
    sql-migration-suffixes: .sql
    sql-migration-prefix: table
    baseline-on-migrate: true
    schemas: public
    validate-migration-naming: true
  datasource:
    url: jdbc:postgresql://babar.db.elephantsql.com:5432/mrzniwhc?socketTimeout=3
    username: mrzniwhc
    password: 3XsZiHozrHTpq8tz9gNE6aY0RZxe9P5T
    driver-class-name: org.postgresql.Driver
  mustache:
    prefix: [classpath:/templates/]
    suffix: .mustache

springdoc:
  api-docs:
    path: /api-docs
