#file: noinspection undefined
spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@contaspix.hqbpdxt.mongodb.net/?retryWrites=true&w=majority
      database: Clients
  rabbitmq:
    addresses: amqps://soiggbyt:9J6xLVyydcoIEuQeMVlrUMBXVyfi-2qK@jackal.rmq.cloudamqp.com/soiggbyt
  flyway:
    enabled: true
    baseline-version: 1
    locations: [classpath:db/migrations]
    sql-migration-suffixes: .sql
    sql-migration-prefix: table
    baseline-on-migrate: true
    schemas: public
    validate-migration-naming: true
  datasource:
    url: jdbc:postgresql://babar.db.elephantsql.com:5432/pwdslund?socketTimeout=3
    username: pwdslund
    password: VEmjS7PHG05ZL4SEq9cfDvEwyoorslFf
    driver-class-name: org.postgresql.Driver
  mustache:
    prefix: [classpath:/templates/]
    suffix: .mustache
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: rauldantas@usp.br
    password: Pfw3zxbONRY2anJH
    protocol: smtp
  main:
    allow-circular-references: true

springdoc:
  api-docs:
    path: /api-docs
